
ifeq ($(findstring sscma_micro, $(LIB_SEL)), sscma_micro)


LIB_SSCMA_MICRO_DEFINES = -DLIB_SSCMA_MICRO -DMA_PLATFORM_HIMAX -DMA_BOARD_GROVE_VISION_AI_V2=1 -DMA_FILESYSTEM_LITTLEFS=1

LIB_SSCMA_MICRO_DIR = $(LIBRARIES_ROOT)/sscma_micro

LIB_SSCMA_MICRO_3RDPARTY_DIR = $(LIB_SSCMA_MICRO_DIR)/3rdparty

LIB_SSCMA_MICRO_3RDPARTY_JSON_INCS_DIR = $(LIB_SSCMA_MICRO_3RDPARTY_DIR)/json/cJSON
LIB_SSCMA_MICRO_3RDPARTY_JSON_SRCS_DIR = $(LIB_SSCMA_MICRO_3RDPARTY_JSON_INCS_DIR)

LIB_SSCMA_MICRO_3RDPARTY_LFS_INCS_DIR = $(LIB_SSCMA_MICRO_3RDPARTY_DIR)/littlefs $(LIB_SSCMA_MICRO_3RDPARTY_DIR)/littlefs/littlefs
LIB_SSCMA_MICRO_3RDPARTY_LFS_SRCS_DIR = $(LIB_SSCMA_MICRO_3RDPARTY_LFS_INCS_DIR)

LIB_SSCMA_MICRO_3RDPARTY_INCS_DIR = $(LIB_SSCMA_MICRO_3RDPARTY_LFS_INCS_DIR) $(LIB_SSCMA_MICRO_3RDPARTY_JSON_INCS_DIR)
LIB_SSCMA_MICRO_3RDPARTY_SRCS_DIR = $(LIB_SSCMA_MICRO_3RDPARTY_LFS_SRCS_DIR) $(LIB_SSCMA_MICRO_3RDPARTY_JSON_SRCS_DIR)
LIB_SSCMA_MICRO_3RDPARTY_ASMSRCS += $(call get_asmsrcs, $(LIB_SSCMA_MICRO_3RDPARTY_SRCS_DIR))
LIB_SSCMA_MICRO_3RDPARTY_CSRCS += $(call get_csrcs, $(LIB_SSCMA_MICRO_3RDPARTY_SRCS_DIR))
LIB_SSCMA_MICRO_3RDPARTY_CXXSRCS += $(call get_cxxsrcs, $(LIB_SSCMA_MICRO_3RDPARTY_SRCS_DIR))

LIB_SSCMA_MICRO_3RDPARTY_ASMOBJS = $(call get_relobjs, $(LIB_SSCMA_MICRO_3RDPARTY_ASMSRCS))
LIB_SSCMA_MICRO_3RDPARTY_COBJS = $(call get_relobjs, $(LIB_SSCMA_MICRO_3RDPARTY_CSRCS))
LIB_SSCMA_MICRO_3RDPARTY_CXXOBJS = $(call get_relobjs, $(LIB_SSCMA_MICRO_3RDPARTY_CXXSRCS))

LIB_SSCMA_MICRO_3RDPARTY_OBJS = $(LIB_SSCMA_MICRO_3RDPARTY_ASMOBJS) $(LIB_SSCMA_MICRO_3RDPARTY_COBJS) $(LIB_SSCMA_MICRO_3RDPARTY_CXXOBJS)

LIB_SSCMA_MICRO_SRCS_DIR = $(LIB_SSCMA_MICRO_DIR)/sscma

LIB_SSCMA_MICRO_SRCS_DIR += $(LIB_SSCMA_MICRO_DIR)/sscma/core
LIB_SSCMA_MICRO_SRCS_DIR += $(LIB_SSCMA_MICRO_DIR)/sscma/core/cv
LIB_SSCMA_MICRO_SRCS_DIR += $(LIB_SSCMA_MICRO_DIR)/sscma/core/engine
LIB_SSCMA_MICRO_SRCS_DIR += $(LIB_SSCMA_MICRO_DIR)/sscma/core/math
LIB_SSCMA_MICRO_SRCS_DIR += $(LIB_SSCMA_MICRO_DIR)/sscma/core/model
LIB_SSCMA_MICRO_SRCS_DIR += $(LIB_SSCMA_MICRO_DIR)/sscma/core/pipeline
LIB_SSCMA_MICRO_SRCS_DIR += $(LIB_SSCMA_MICRO_DIR)/sscma/core/utils

LIB_SSCMA_MICRO_SRCS_DIR += $(LIB_SSCMA_MICRO_DIR)/sscma/porting
LIB_SSCMA_MICRO_SRCS_DIR += $(LIB_SSCMA_MICRO_DIR)/sscma/porting/drivers
LIB_SSCMA_MICRO_SRCS_DIR += $(LIB_SSCMA_MICRO_DIR)/sscma/porting/drivers/bd

LIB_SSCMA_MICRO_SRCS_DIR += $(LIB_SSCMA_MICRO_DIR)/sscma/porting/osal
LIB_SSCMA_MICRO_SRCS_DIR += $(LIB_SSCMA_MICRO_DIR)/sscma/porting/himax/we2
LIB_SSCMA_MICRO_SRCS_DIR += $(LIB_SSCMA_MICRO_DIR)/sscma/porting/himax/we2/configs
LIB_SSCMA_MICRO_SRCS_DIR += $(LIB_SSCMA_MICRO_DIR)/sscma/porting/himax/we2/drivers
LIB_SSCMA_MICRO_SRCS_DIR += $(LIB_SSCMA_MICRO_DIR)/sscma/porting/himax/we2/drivers/bd
LIB_SSCMA_MICRO_SRCS_DIR += $(LIB_SSCMA_MICRO_DIR)/sscma/porting/himax/we2/drivers/camera

LIB_SSCMA_MICRO_SRCS_DIR += $(LIB_SSCMA_MICRO_DIR)/sscma/server
LIB_SSCMA_MICRO_SRCS_DIR += $(LIB_SSCMA_MICRO_DIR)/sscma/server/at
LIB_SSCMA_MICRO_SRCS_DIR += $(LIB_SSCMA_MICRO_DIR)/sscma/server/at/codec
LIB_SSCMA_MICRO_SRCS_DIR += $(LIB_SSCMA_MICRO_DIR)/sscma/server/at/callback

LIB_SSCMA_MICRO_INCS_DIR = $(LIB_SSCMA_MICRO_SRCS_DIR)

LIB_SSCMA_MICRO_ASMSRCS = $(call get_asmsrcs, $(LIB_SSCMA_MICRO_SRCS_DIR))
LIB_SSCMA_MICRO_CSRCS = $(call get_csrcs, $(LIB_SSCMA_MICRO_SRCS_DIR))
LIB_SSCMA_MICRO_CXXSRCS = $(call get_cxxsrcs, $(LIB_SSCMA_MICRO_SRCS_DIR))

LIB_SSCMA_MICRO_ASMOBJS = $(call get_relobjs, $(LIB_SSCMA_MICRO_ASMSRCS))
LIB_SSCMA_MICRO_COBJS = $(call get_relobjs, $(LIB_SSCMA_MICRO_CSRCS))
LIB_SSCMA_MICRO_CXXOBJS = $(call get_relobjs, $(LIB_SSCMA_MICRO_CXXSRCS))

LIB_SSCMA_MICRO_OBJS = $(LIB_SSCMA_MICRO_ASMOBJS) $(LIB_SSCMA_MICRO_COBJS) $(LIB_SSCMA_MICRO_CXXOBJS) $(LIB_SSCMA_MICRO_3RDPARTY_OBJS)

LIB_SSCMA_MICRO_DEPS = $(call get_deps, $(LIB_SSCMA_MICRO_OBJS))

ifeq ($(C_LIB_FORCE_PREBUILT), y)
	override LIB_SSCMA_MICRO_OBJS :=
endif
SSCMA_MICRO_LIB_NAME = libsscma_micro.a
LIB_SSCMA_MICRO := $(subst /,$(PS), $(strip $(OUT_DIR)/$(SSCMA_MICRO_LIB_NAME)))

$(LIB_SSCMA_MICRO): $(LIB_SSCMA_MICRO_OBJS)
	$(TRACE_ARCHIVE)
ifeq "$(strip $(LIB_SSCMA_MICRO_OBJS))" ""
	$(CP) $(PREBUILT_LIB) $(SSCMA_MICRO_LIB_NAME) $(LIB_SSCMA_MICRO)
else
	$(Q)$(AR) $(AR_OPT) $@ $(LIB_SSCMA_MICRO_OBJS)
	$(CP) $(LIB_SSCMA_MICRO) $(PREBUILT_LIB)$(SSCMA_MICRO_LIB_NAME)
endif

LIB_INCDIR += $(LIB_SSCMA_MICRO_3RDPARTY_INCS_DIR)
LIB_INCDIR += $(LIB_SSCMA_MICRO_INCS_DIR)
LIB_ASMSRCDIR += $(LIB_SSCMA_MICRO_3RDPARTY_ASMSRCS)
LIB_ASMSRCDIR += $(LIB_SSCMA_MICRO_ASMSRCS)
LIB_CSRCDIR += $(LIB_SSCMA_MICRO_3RDPARTY_CSRCS)
LIB_CSRCDIR += $(LIB_SSCMA_MICRO_CSRCS)
LIB_CXXSRCDIR += $(LIB_SSCMA_MICRO_3RDPARTY_CXXSRCS)
LIB_CXXSRCDIR += $(LIB_SSCMA_MICRO_CXXSRCS)

LIB_CSRCS += $(LIB_SSCMA_MICRO_3RDPARTY_CSRCS)
LIB_CSRCS += $(LIB_SSCMA_MICRO_CSRCS)
LIB_CXXSRCS += $(LIB_SSCMA_MICRO_3RDPARTY_CXXSRCS)
LIB_CXXSRCS += $(LIB_SSCMA_MICRO_CXXSRCS)
LIB_ASMSRCS += $(LIB_SSCMA_MICRO_3RDPARTY_ASMSRCS)
LIB_ASMSRCS += $(LIB_SSCMA_MICRO_ASMSRCS)
LIB_ALLSRCS += $(LIB_SSCMA_MICRO_3RDPARTY_ASMSRCS) $(LIB_SSCMA_MICRO_3RDPARTY_CSRCS) $(LIB_SSCMA_MICRO_3RDPARTY_CXXSRCS)
LIB_ALLSRCS += $(LIB_SSCMA_MICRO_ASMSRCS) $(LIB_SSCMA_MICRO_CSRCS) $(LIB_SSCMA_MICRO_CXXSRCS)

LIB_ASMOBJS += $(LIB_SSCMA_MICRO_3RDPARTY_ASMOBJS)
LIB_ASMOBJS += $(LIB_SSCMA_MICRO_ASMOBJS)
LIB_COBJS += $(LIB_SSCMA_MICRO_3RDPARTY_COBJS)
LIB_COBJS += $(LIB_SSCMA_MICRO_COBJS)
LIB_CXXOBJS += $(LIB_SSCMA_MICRO_3RDPARTY_CXXOBJS)
LIB_CXXOBJS += $(LIB_SSCMA_MICRO_CXXOBJS)

LIB_DEFINES += $(LIB_SSCMA_MICRO_DEFINES)
LIB_DEPS += $(LIB_SSCMA_MICRO_DEPS)
LIB_LIBS += $(LIB_SSCMA_MICRO)

endif

