.TH "sscma/callback/algorithm.hpp" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sscma/callback/algorithm.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <atomic>\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'sscma/callback/internal/algorithm_config_helper\&.hpp'\fP
.br
\fC#include 'sscma/definations\&.hpp'\fP
.br
\fC#include 'sscma/static_resourse\&.hpp'\fP
.br
\fC#include 'sscma/utility\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsscma\fP"
.br
.ti -1c
.RI " \fBsscma::callback\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsscma::callback::get_available_algorithms\fP (const std::string &cmd)"
.br
.ti -1c
.RI "void \fBsscma::callback::set_algorithm\fP (const std::string &cmd, \fBel_algorithm_type_t\fP algorithm_type)"
.br
.ti -1c
.RI "void \fBsscma::callback::get_algorithm_info\fP (const std::string &cmd)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
