.TH "edgelab::types" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
edgelab::types
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBel_algorithm_info_t\fP"
.br
.ti -1c
.RI "struct \fBel_algorithm_fomo_config_t\fP"
.br
.ti -1c
.RI "struct \fBel_algorithm_imcls_config_t\fP"
.br
.ti -1c
.RI "struct \fBel_algorithm_pfld_config_t\fP"
.br
.ti -1c
.RI "struct \fBel_algorithm_yolo_config_t\fP"
.br
.ti -1c
.RI "struct \fBel_storage_kv_t\fP"
.br
.ti -1c
.RI "struct \fBb16_t\fP"
.br
.ti -1c
.RI "struct \fBb24_t\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct EL_ATTR_PACKED \fBedgelab::types::b16_t\fP \fBb16_t\fP"
.br
.ti -1c
.RI "typedef struct EL_ATTR_PACKED \fBedgelab::types::b24_t\fP \fBb24_t\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct EL_ATTR_PACKED \fBedgelab::types::b16_t\fP \fBedgelab::types::b16_t\fP"

.SS "typedef struct EL_ATTR_PACKED \fBedgelab::types::b24_t\fP \fBedgelab::types::b24_t\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
