.TH "edgelab::Models" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
edgelab::Models
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <el_data_models\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModels\fP ()"
.br
.ti -1c
.RI "\fB~Models\fP ()"
.br
.ti -1c
.RI "\fBModels\fP (const \fBModels\fP &)=delete"
.br
.ti -1c
.RI "\fBModels\fP & \fBoperator=\fP (const \fBModels\fP &)=delete"
.br
.ti -1c
.RI "\fBel_err_code_t\fP \fBinit\fP (const char *partition_name=\fBCONFIG_EL_MODEL_PARTITION_NAME\fP, const \fBel_model_format_v\fP &model_format=\fBEL_MODEL_FMT_PACKED_TFLITE\fP|\fBEL_MODEL_FMT_PLAIN_TFLITE\fP)"
.br
.ti -1c
.RI "void \fBdeinit\fP ()"
.br
.ti -1c
.RI "size_t \fBseek_models_from_flash\fP (const \fBel_model_format_v\fP &model_format)"
.br
.ti -1c
.RI "bool \fBhas_model\fP (\fBel_model_id_t\fP model_id) const"
.br
.ti -1c
.RI "\fBel_err_code_t\fP \fBget\fP (\fBel_model_id_t\fP model_id, \fBel_model_info_t\fP &model_info) const"
.br
.ti -1c
.RI "\fBel_model_info_t\fP \fBget_model_info\fP (\fBel_model_id_t\fP model_id) const"
.br
.ti -1c
.RI "const std::forward_list< \fBel_model_info_t\fP > & \fBget_all_model_info\fP () const"
.br
.ti -1c
.RI "size_t \fBget_all_model_info_size\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBm_seek_packed_models_from_flash\fP ()"
.br
.ti -1c
.RI "void \fBm_seek_plain_models_from_flash\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "edgelab::Models::Models ()"

.SS "edgelab::Models::~Models ()"

.SS "edgelab::Models::Models (const \fBModels\fP &)\fC [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void edgelab::Models::deinit ()"

.SS "\fBel_err_code_t\fP edgelab::Models::get (\fBel_model_id_t\fP model_id, \fBel_model_info_t\fP & model_info) const"

.SS "const std::forward_list< \fBel_model_info_t\fP > & edgelab::Models::get_all_model_info () const"

.SS "size_t edgelab::Models::get_all_model_info_size () const"

.SS "\fBel_model_info_t\fP edgelab::Models::get_model_info (\fBel_model_id_t\fP model_id) const"

.SS "bool edgelab::Models::has_model (\fBel_model_id_t\fP model_id) const"

.SS "\fBel_err_code_t\fP edgelab::Models::init (const char * partition_name = \fC\fBCONFIG_EL_MODEL_PARTITION_NAME\fP\fP, const \fBel_model_format_v\fP & model_format = \fC\fBEL_MODEL_FMT_PACKED_TFLITE\fP | \fBEL_MODEL_FMT_PLAIN_TFLITE\fP\fP)"

.SS "void edgelab::Models::m_seek_packed_models_from_flash ()\fC [protected]\fP"

.SS "void edgelab::Models::m_seek_plain_models_from_flash ()\fC [protected]\fP"

.SS "\fBModels\fP& edgelab::Models::operator= (const \fBModels\fP &)\fC [delete]\fP"

.SS "size_t edgelab::Models::seek_models_from_flash (const \fBel_model_format_v\fP & model_format)"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
