.TH "edgelab::AlgorithmIMCLS" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
edgelab::AlgorithmIMCLS
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <el_algorithm_imcls\&.h>\fP
.PP
Inherits \fBedgelab::base::Algorithm\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBImageType\fP = \fBel_img_t\fP"
.br
.ti -1c
.RI "using \fBClassType\fP = \fBel_class_t\fP"
.br
.ti -1c
.RI "using \fBConfigType\fP = \fBel_algorithm_imcls_config_t\fP"
.br
.ti -1c
.RI "using \fBScoreType\fP = decltype(\fBel_algorithm_imcls_config_t::score_threshold\fP)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAlgorithmIMCLS\fP (\fBEngineType\fP *engine, \fBScoreType\fP score_threshold=50)"
.br
.ti -1c
.RI "\fBAlgorithmIMCLS\fP (\fBEngineType\fP *engine, const \fBConfigType\fP &config)"
.br
.ti -1c
.RI "\fB~AlgorithmIMCLS\fP ()"
.br
.ti -1c
.RI "\fBel_err_code_t\fP \fBrun\fP (\fBImageType\fP *input)"
.br
.ti -1c
.RI "const std::forward_list< \fBClassType\fP > & \fBget_results\fP () const"
.br
.ti -1c
.RI "void \fBset_score_threshold\fP (\fBScoreType\fP threshold)"
.br
.ti -1c
.RI "\fBScoreType\fP \fBget_score_threshold\fP () const"
.br
.ti -1c
.RI "void \fBset_algorithm_config\fP (const \fBConfigType\fP &config)"
.br
.ti -1c
.RI "\fBConfigType\fP \fBget_algorithm_config\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBis_model_valid\fP (const \fBEngineType\fP *engine)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBInfoType\fP \fBalgorithm_info\fP {\fBel_algorithm_imcls_config_t::info\fP}"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "\fBel_err_code_t\fP \fBpreprocess\fP () override"
.br
.ti -1c
.RI "\fBel_err_code_t\fP \fBpostprocess\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBedgelab::AlgorithmIMCLS::ClassType\fP =  \fBel_class_t\fP"

.SS "using \fBedgelab::AlgorithmIMCLS::ConfigType\fP =  \fBel_algorithm_imcls_config_t\fP"

.SS "using \fBedgelab::AlgorithmIMCLS::ImageType\fP =  \fBel_img_t\fP"

.SS "using \fBedgelab::AlgorithmIMCLS::ScoreType\fP =  decltype(\fBel_algorithm_imcls_config_t::score_threshold\fP)"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "edgelab::AlgorithmIMCLS::AlgorithmIMCLS (\fBEngineType\fP * engine, \fBScoreType\fP score_threshold = \fC50\fP)"

.SS "edgelab::AlgorithmIMCLS::AlgorithmIMCLS (\fBEngineType\fP * engine, const \fBConfigType\fP & config)"

.SS "edgelab::AlgorithmIMCLS::~AlgorithmIMCLS ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBAlgorithmIMCLS::ConfigType\fP edgelab::AlgorithmIMCLS::get_algorithm_config () const"

.SS "const std::forward_list< \fBAlgorithmIMCLS::ClassType\fP > & edgelab::AlgorithmIMCLS::get_results () const"

.SS "\fBAlgorithmIMCLS::ScoreType\fP edgelab::AlgorithmIMCLS::get_score_threshold () const"

.SS "void edgelab::AlgorithmIMCLS::init ()\fC [inline]\fP, \fC [protected]\fP"

.SS "bool edgelab::AlgorithmIMCLS::is_model_valid (const \fBEngineType\fP * engine)\fC [static]\fP"

.SS "\fBel_err_code_t\fP edgelab::AlgorithmIMCLS::postprocess ()\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBedgelab::base::Algorithm\fP\&.
.SS "\fBel_err_code_t\fP edgelab::AlgorithmIMCLS::preprocess ()\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBedgelab::base::Algorithm\fP\&.
.SS "\fBel_err_code_t\fP edgelab::AlgorithmIMCLS::run (\fBImageType\fP * input)"

.SS "void edgelab::AlgorithmIMCLS::set_algorithm_config (const \fBConfigType\fP & config)"

.SS "void edgelab::AlgorithmIMCLS::set_score_threshold (\fBScoreType\fP threshold)"

.SH "Member Data Documentation"
.PP 
.SS "\fBAlgorithmIMCLS::InfoType\fP edgelab::AlgorithmIMCLS::algorithm_info {\fBel_algorithm_imcls_config_t::info\fP}\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
