.TH "edgelab::Guard< T >" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
edgelab::Guard< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <el_guard\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGuard\fP (const T &mutex) noexcept"
.br
.ti -1c
.RI "\fB~Guard\fP () noexcept"
.br
.ti -1c
.RI "\fBGuard\fP (const \fBGuard\fP &)=delete"
.br
.ti -1c
.RI "\fBGuard\fP & \fBoperator=\fP (const \fBGuard\fP &)=delete"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBedgelab::Guard\fP< T >::\fBGuard\fP (const T & mutex)\fC [inline]\fP, \fC [explicit]\fP, \fC [noexcept]\fP"

.SS "template<typename T > \fBedgelab::Guard\fP< T >::~\fBGuard\fP ()\fC [inline]\fP, \fC [noexcept]\fP"

.SS "template<typename T > \fBedgelab::Guard\fP< T >::\fBGuard\fP (const \fBGuard\fP< T > &)\fC [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T > \fBGuard\fP& \fBedgelab::Guard\fP< T >::operator= (const \fBGuard\fP< T > &)\fC [delete]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
