.TH "edgelab::AlgorithmPFLD" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
edgelab::AlgorithmPFLD
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <el_algorithm_pfld\&.h>\fP
.PP
Inherits \fBedgelab::base::Algorithm\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBImageType\fP = \fBel_img_t\fP"
.br
.ti -1c
.RI "using \fBPointType\fP = \fBel_point_t\fP"
.br
.ti -1c
.RI "using \fBConfigType\fP = \fBel_algorithm_pfld_config_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAlgorithmPFLD\fP (\fBEngineType\fP *engine)"
.br
.ti -1c
.RI "\fBAlgorithmPFLD\fP (\fBEngineType\fP *engine, const \fBConfigType\fP &config)"
.br
.ti -1c
.RI "\fB~AlgorithmPFLD\fP ()"
.br
.ti -1c
.RI "\fBel_err_code_t\fP \fBrun\fP (\fBImageType\fP *input)"
.br
.ti -1c
.RI "const std::forward_list< \fBPointType\fP > & \fBget_results\fP () const"
.br
.ti -1c
.RI "void \fBset_algorithm_config\fP (const \fBConfigType\fP &)"
.br
.ti -1c
.RI "\fBConfigType\fP \fBget_algorithm_config\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBis_model_valid\fP (const \fBEngineType\fP *engine)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBInfoType\fP \fBalgorithm_info\fP {\fBel_algorithm_pfld_config_t::info\fP}"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "\fBel_err_code_t\fP \fBpreprocess\fP () override"
.br
.ti -1c
.RI "\fBel_err_code_t\fP \fBpostprocess\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBedgelab::AlgorithmPFLD::ConfigType\fP =  \fBel_algorithm_pfld_config_t\fP"

.SS "using \fBedgelab::AlgorithmPFLD::ImageType\fP =  \fBel_img_t\fP"

.SS "using \fBedgelab::AlgorithmPFLD::PointType\fP =  \fBel_point_t\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "edgelab::AlgorithmPFLD::AlgorithmPFLD (\fBEngineType\fP * engine)"

.SS "edgelab::AlgorithmPFLD::AlgorithmPFLD (\fBEngineType\fP * engine, const \fBConfigType\fP & config)"

.SS "edgelab::AlgorithmPFLD::~AlgorithmPFLD ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBAlgorithmPFLD::ConfigType\fP edgelab::AlgorithmPFLD::get_algorithm_config () const"

.SS "const std::forward_list< \fBAlgorithmPFLD::PointType\fP > & edgelab::AlgorithmPFLD::get_results () const"

.SS "void edgelab::AlgorithmPFLD::init ()\fC [inline]\fP, \fC [protected]\fP"

.SS "bool edgelab::AlgorithmPFLD::is_model_valid (const \fBEngineType\fP * engine)\fC [static]\fP"

.SS "\fBel_err_code_t\fP edgelab::AlgorithmPFLD::postprocess ()\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBedgelab::base::Algorithm\fP\&.
.SS "\fBel_err_code_t\fP edgelab::AlgorithmPFLD::preprocess ()\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBedgelab::base::Algorithm\fP\&.
.SS "\fBel_err_code_t\fP edgelab::AlgorithmPFLD::run (\fBImageType\fP * input)"

.SS "void edgelab::AlgorithmPFLD::set_algorithm_config (const \fBConfigType\fP &)"

.SH "Member Data Documentation"
.PP 
.SS "\fBAlgorithmPFLD::InfoType\fP edgelab::AlgorithmPFLD::algorithm_info {\fBel_algorithm_pfld_config_t::info\fP}\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
