.TH "edgelab::types::el_storage_kv_t< ValueType >" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
edgelab::types::el_storage_kv_t< ValueType >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <el_data_storage\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBel_storage_kv_t\fP (const char *key_, ValueType &&value_, size_t size_=sizeof(ValueType)) noexcept"
.br
.ti -1c
.RI "\fB~el_storage_kv_t\fP ()=default"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBkey\fP"
.br
.ti -1c
.RI "ValueType \fBvalue\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename ValueType > \fBedgelab::types::el_storage_kv_t\fP< ValueType >::\fBel_storage_kv_t\fP (const char * key_, ValueType && value_, size_t size_ = \fCsizeof(ValueType)\fP)\fC [inline]\fP, \fC [explicit]\fP, \fC [noexcept]\fP"

.SS "template<typename ValueType > \fBedgelab::types::el_storage_kv_t\fP< ValueType >::~\fBel_storage_kv_t\fP ()\fC [default]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename ValueType > const char* \fBedgelab::types::el_storage_kv_t\fP< ValueType >::key"

.SS "template<typename ValueType > size_t \fBedgelab::types::el_storage_kv_t\fP< ValueType >::size"

.SS "template<typename ValueType > ValueType \fBedgelab::types::el_storage_kv_t\fP< ValueType >::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
