.TH "edgelab::types::el_algorithm_info_t" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
edgelab::types::el_algorithm_info_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <el_algorithm_base\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBel_algorithm_type_t\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBel_algorithm_cat_t\fP \fBcategroy\fP"
.br
.ti -1c
.RI "\fBel_sensor_type_t\fP \fBinput_from\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBel_algorithm_cat_t\fP edgelab::types::el_algorithm_info_t::categroy"

.SS "\fBel_sensor_type_t\fP edgelab::types::el_algorithm_info_t::input_from"

.SS "\fBel_algorithm_type_t\fP edgelab::types::el_algorithm_info_t::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
