.TH "edgelab::utility" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
edgelab::utility
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBel_algorithm_type_t\fP \fBel_algorithm_type_from_engine\fP (const \fBEngine\fP *engine)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBel_algorithm_type_t\fP edgelab::utility::el_algorithm_type_from_engine (const \fBEngine\fP * engine)"

.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
