.TH "edgelab::CameraEsp" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
edgelab::CameraEsp
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <el_camera_esp\&.h>\fP
.PP
Inherits \fBedgelab::Camera\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCameraEsp\fP ()=default"
.br
.ti -1c
.RI "\fB~CameraEsp\fP ()=default"
.br
.ti -1c
.RI "\fBel_err_code_t\fP \fBinit\fP (size_t width, size_t height) override"
.br
.ti -1c
.RI "\fBel_err_code_t\fP \fBdeinit\fP () override"
.br
.ti -1c
.RI "\fBel_err_code_t\fP \fBstart_stream\fP () override"
.br
.ti -1c
.RI "\fBel_err_code_t\fP \fBstop_stream\fP () override"
.br
.ti -1c
.RI "\fBel_err_code_t\fP \fBget_frame\fP (\fBel_img_t\fP *img) override"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "framesize_t \fBfit_resolution\fP (size_t width, size_t height)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "edgelab::CameraEsp::CameraEsp ()\fC [default]\fP"

.SS "edgelab::CameraEsp::~CameraEsp ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBel_err_code_t\fP edgelab::CameraEsp::deinit ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBedgelab::Camera\fP\&.
.SS "framesize_t edgelab::CameraEsp::fit_resolution (size_t width, size_t height)\fC [protected]\fP"

.SS "\fBel_err_code_t\fP edgelab::CameraEsp::get_frame (\fBel_img_t\fP * img)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBedgelab::Camera\fP\&.
.SS "\fBel_err_code_t\fP edgelab::CameraEsp::init (size_t width, size_t height)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBedgelab::Camera\fP\&.
.SS "\fBel_err_code_t\fP edgelab::CameraEsp::start_stream ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBedgelab::Camera\fP\&.
.SS "\fBel_err_code_t\fP edgelab::CameraEsp::stop_stream ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBedgelab::Camera\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
