.TH "edgelab::Camera" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
edgelab::Camera
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <el_camera\&.h>\fP
.PP
Inherited by \fBedgelab::CameraEsp\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCamera\fP ()"
.br
.ti -1c
.RI "virtual \fB~Camera\fP ()=default"
.br
.ti -1c
.RI "virtual \fBel_err_code_t\fP \fBinit\fP (size_t width, size_t height)=0"
.br
.ti -1c
.RI "virtual \fBel_err_code_t\fP \fBdeinit\fP ()=0"
.br
.ti -1c
.RI "virtual \fBel_err_code_t\fP \fBstart_stream\fP ()=0"
.br
.ti -1c
.RI "virtual \fBel_err_code_t\fP \fBstop_stream\fP ()=0"
.br
.ti -1c
.RI "virtual \fBel_err_code_t\fP \fBget_frame\fP (\fBel_img_t\fP *img)=0"
.br
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.ti -1c
.RI "bool \fBis_streaming\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fB_is_present\fP"
.br
.ti -1c
.RI "bool \fB_is_streaming\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "edgelab::Camera::Camera ()\fC [inline]\fP"

.SS "virtual edgelab::Camera::~Camera ()\fC [virtual]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBel_err_code_t\fP edgelab::Camera::deinit ()\fC [pure virtual]\fP"

.PP
Implemented in \fBedgelab::CameraEsp\fP\&.
.SS "virtual \fBel_err_code_t\fP edgelab::Camera::get_frame (\fBel_img_t\fP * img)\fC [pure virtual]\fP"

.PP
Implemented in \fBedgelab::CameraEsp\fP\&.
.SS "virtual \fBel_err_code_t\fP edgelab::Camera::init (size_t width, size_t height)\fC [pure virtual]\fP"

.PP
Implemented in \fBedgelab::CameraEsp\fP\&.
.SS "bool edgelab::Camera::is_streaming () const\fC [inline]\fP"

.SS "edgelab::Camera::operator bool () const\fC [inline]\fP"

.SS "virtual \fBel_err_code_t\fP edgelab::Camera::start_stream ()\fC [pure virtual]\fP"

.PP
Implemented in \fBedgelab::CameraEsp\fP\&.
.SS "virtual \fBel_err_code_t\fP edgelab::Camera::stop_stream ()\fC [pure virtual]\fP"

.PP
Implemented in \fBedgelab::CameraEsp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool edgelab::Camera::_is_present\fC [protected]\fP"

.SS "bool edgelab::Camera::_is_streaming\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
