.TH "edgelab::DeviceEsp" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
edgelab::DeviceEsp
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <el_device_esp\&.h>\fP
.PP
Inherits \fBedgelab::Device\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDeviceEsp\fP ()"
.br
.ti -1c
.RI "\fB~DeviceEsp\fP ()=default"
.br
.ti -1c
.RI "void \fBrestart\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "edgelab::DeviceEsp::DeviceEsp ()"

.SS "edgelab::DeviceEsp::~DeviceEsp ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void edgelab::DeviceEsp::restart ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBedgelab::Device\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
