.TH "edgelab::AlgorithmDelegate" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
edgelab::AlgorithmDelegate
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <el_algorithm_delegate\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBInfoType\fP = \fBel_algorithm_info_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~AlgorithmDelegate\fP ()=default"
.br
.ti -1c
.RI "\fBInfoType\fP \fBget_algorithm_info\fP (\fBel_algorithm_type_t\fP type) const"
.br
.ti -1c
.RI "const std::forward_list< const \fBInfoType\fP * > & \fBget_all_algorithm_info\fP () const"
.br
.ti -1c
.RI "size_t \fBget_all_algorithm_info_count\fP () const"
.br
.ti -1c
.RI "bool \fBhas_algorithm\fP (\fBel_algorithm_type_t\fP type) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBAlgorithmDelegate\fP * \fBget_delegate\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBAlgorithmDelegate\fP ()"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBedgelab::AlgorithmDelegate::InfoType\fP =  \fBel_algorithm_info_t\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "edgelab::AlgorithmDelegate::~AlgorithmDelegate ()\fC [default]\fP"

.SS "edgelab::AlgorithmDelegate::AlgorithmDelegate ()\fC [protected]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBAlgorithmDelegate::InfoType\fP edgelab::AlgorithmDelegate::get_algorithm_info (\fBel_algorithm_type_t\fP type) const"

.SS "const std::forward_list< const \fBAlgorithmDelegate::InfoType\fP * > & edgelab::AlgorithmDelegate::get_all_algorithm_info () const"

.SS "size_t edgelab::AlgorithmDelegate::get_all_algorithm_info_count () const"

.SS "\fBAlgorithmDelegate\fP * edgelab::AlgorithmDelegate::get_delegate ()\fC [static]\fP"

.SS "bool edgelab::AlgorithmDelegate::has_algorithm (\fBel_algorithm_type_t\fP type) const"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
