.TH "edgelab::types::el_algorithm_yolo_config_t" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
edgelab::types::el_algorithm_yolo_config_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <el_algorithm_yolo\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBscore_threshold\fP = 50"
.br
.ti -1c
.RI "uint8_t \fBiou_threshold\fP = 45"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr \fBel_algorithm_info_t\fP \fBinfo\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "constexpr \fBel_algorithm_info_t\fP edgelab::types::el_algorithm_yolo_config_t::info\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
{
      \&.type = EL_ALGO_TYPE_YOLO, \&.categroy = EL_ALGO_CAT_DET, \&.input_from = EL_SENSOR_TYPE_CAM}
.fi
.SS "uint8_t edgelab::types::el_algorithm_yolo_config_t::iou_threshold = 45"

.SS "uint8_t edgelab::types::el_algorithm_yolo_config_t::score_threshold = 50"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
