.TH "edgelab::DisplayEsp" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
edgelab::DisplayEsp
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <el_display_esp\&.h>\fP
.PP
Inherits \fBedgelab::Display\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDisplayEsp\fP ()=default"
.br
.ti -1c
.RI "\fB~DisplayEsp\fP ()=default"
.br
.ti -1c
.RI "\fBel_err_code_t\fP \fBinit\fP () override"
.br
.ti -1c
.RI "\fBel_err_code_t\fP \fBdeinit\fP () override"
.br
.ti -1c
.RI "\fBel_err_code_t\fP \fBshow\fP (const \fBel_img_t\fP *img) override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "edgelab::DisplayEsp::DisplayEsp ()\fC [default]\fP"

.SS "edgelab::DisplayEsp::~DisplayEsp ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBel_err_code_t\fP edgelab::DisplayEsp::deinit ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBedgelab::Display\fP\&.
.SS "\fBel_err_code_t\fP edgelab::DisplayEsp::init ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBedgelab::Display\fP\&.
.SS "\fBel_err_code_t\fP edgelab::DisplayEsp::show (const \fBel_img_t\fP * img)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBedgelab::Display\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
