.TH "edgelab::Serial" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
edgelab::Serial
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <el_serial\&.h>\fP
.PP
Inherits \fBedgelab::Transport\fP\&.
.PP
Inherited by \fBedgelab::SerialEsp\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSerial\fP ()=default"
.br
.ti -1c
.RI "virtual \fB~Serial\fP ()=default"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "edgelab::Serial::Serial ()\fC [default]\fP"

.SS "virtual edgelab::Serial::~Serial ()\fC [virtual]\fP, \fC [default]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
