.TH "edgelab::Mutex" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
edgelab::Mutex
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <el_mutex\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMutex\fP () noexcept"
.br
.ti -1c
.RI "\fB~Mutex\fP () noexcept"
.br
.ti -1c
.RI "void \fBlock\fP () const"
.br
.ti -1c
.RI "void \fBunlock\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "edgelab::Mutex::Mutex ()\fC [inline]\fP, \fC [noexcept]\fP"

.SS "edgelab::Mutex::~Mutex ()\fC [inline]\fP, \fC [noexcept]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void edgelab::Mutex::lock () const\fC [inline]\fP"

.SS "void edgelab::Mutex::unlock () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
