.TH "edgelab::Transport" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
edgelab::Transport
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <el_transport\&.h>\fP
.PP
Inherited by \fBedgelab::Serial\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransport\fP ()"
.br
.ti -1c
.RI "virtual \fB~Transport\fP ()=default"
.br
.ti -1c
.RI "virtual \fBel_err_code_t\fP \fBinit\fP ()=0"
.br
.ti -1c
.RI "virtual \fBel_err_code_t\fP \fBdeinit\fP ()=0"
.br
.ti -1c
.RI "virtual \fBel_err_code_t\fP \fBread_bytes\fP (char *buffer, size_t size)=0"
.br
.ti -1c
.RI "virtual \fBel_err_code_t\fP \fBsend_bytes\fP (const char *buffer, size_t size)=0"
.br
.ti -1c
.RI "virtual char \fBecho\fP (bool only_visible=true)=0"
.br
.ti -1c
.RI "virtual char \fBget_char\fP ()=0"
.br
.ti -1c
.RI "virtual size_t \fBget_line\fP (char *buffer, size_t size, const char delim=0x0d)=0"
.br
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fB_is_present\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "edgelab::Transport::Transport ()\fC [inline]\fP"

.SS "virtual edgelab::Transport::~Transport ()\fC [virtual]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBel_err_code_t\fP edgelab::Transport::deinit ()\fC [pure virtual]\fP"

.PP
Implemented in \fBedgelab::SerialEsp\fP\&.
.SS "virtual char edgelab::Transport::echo (bool only_visible = \fCtrue\fP)\fC [pure virtual]\fP"

.PP
Implemented in \fBedgelab::SerialEsp\fP\&.
.SS "virtual char edgelab::Transport::get_char ()\fC [pure virtual]\fP"

.PP
Implemented in \fBedgelab::SerialEsp\fP\&.
.SS "virtual size_t edgelab::Transport::get_line (char * buffer, size_t size, const char delim = \fC0x0d\fP)\fC [pure virtual]\fP"

.PP
Implemented in \fBedgelab::SerialEsp\fP\&.
.SS "virtual \fBel_err_code_t\fP edgelab::Transport::init ()\fC [pure virtual]\fP"

.PP
Implemented in \fBedgelab::SerialEsp\fP\&.
.SS "edgelab::Transport::operator bool () const\fC [inline]\fP"

.SS "virtual \fBel_err_code_t\fP edgelab::Transport::read_bytes (char * buffer, size_t size)\fC [pure virtual]\fP"

.PP
Implemented in \fBedgelab::SerialEsp\fP\&.
.SS "virtual \fBel_err_code_t\fP edgelab::Transport::send_bytes (const char * buffer, size_t size)\fC [pure virtual]\fP"

.PP
Implemented in \fBedgelab::SerialEsp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool edgelab::Transport::_is_present\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
