.TH "edgelab::types::b16_t" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
edgelab::types::b16_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBb0_8\fP"
.br
.ti -1c
.RI "uint8_t \fBb8_16\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint8_t edgelab::types::b16_t::b0_8"

.SS "uint8_t edgelab::types::b16_t::b8_16"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
