.TH "edgelab::SerialEsp" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
edgelab::SerialEsp
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <el_serial_esp\&.h>\fP
.PP
Inherits \fBedgelab::Serial\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSerialEsp\fP (usb_serial_jtag_driver_config_t driver_config=USB_SERIAL_JTAG_DRIVER_CONFIG_DEFAULT())"
.br
.ti -1c
.RI "\fB~SerialEsp\fP () override"
.br
.ti -1c
.RI "\fBel_err_code_t\fP \fBinit\fP () override"
.br
.ti -1c
.RI "\fBel_err_code_t\fP \fBdeinit\fP () override"
.br
.ti -1c
.RI "char \fBecho\fP (bool only_visible=true) override"
.br
.ti -1c
.RI "char \fBget_char\fP () override"
.br
.ti -1c
.RI "size_t \fBget_line\fP (char *buffer, size_t size, const char delim=0x0d) override"
.br
.ti -1c
.RI "\fBel_err_code_t\fP \fBread_bytes\fP (char *buffer, size_t size) override"
.br
.ti -1c
.RI "\fBel_err_code_t\fP \fBsend_bytes\fP (const char *buffer, size_t size) override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "edgelab::SerialEsp::SerialEsp (usb_serial_jtag_driver_config_t driver_config = \fCUSB_SERIAL_JTAG_DRIVER_CONFIG_DEFAULT()\fP)"

.SS "edgelab::SerialEsp::~SerialEsp ()\fC [override]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBel_err_code_t\fP edgelab::SerialEsp::deinit ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBedgelab::Transport\fP\&.
.SS "char edgelab::SerialEsp::echo (bool only_visible = \fCtrue\fP)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBedgelab::Transport\fP\&.
.SS "char edgelab::SerialEsp::get_char ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBedgelab::Transport\fP\&.
.SS "size_t edgelab::SerialEsp::get_line (char * buffer, size_t size, const char delim = \fC0x0d\fP)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBedgelab::Transport\fP\&.
.SS "\fBel_err_code_t\fP edgelab::SerialEsp::init ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBedgelab::Transport\fP\&.
.SS "\fBel_err_code_t\fP edgelab::SerialEsp::read_bytes (char * buffer, size_t size)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBedgelab::Transport\fP\&.
.SS "\fBel_err_code_t\fP edgelab::SerialEsp::send_bytes (const char * buffer, size_t size)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBedgelab::Transport\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
