.TH "core/algorithm/el_algorithm_yolo.cpp" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/algorithm/el_algorithm_yolo.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'el_algorithm_yolo\&.h'\fP
.br
\fC#include <type_traits>\fP
.br
\fC#include 'core/el_common\&.h'\fP
.br
\fC#include 'core/el_debug\&.h'\fP
.br
\fC#include 'core/utils/el_cv\&.h'\fP
.br
\fC#include 'core/utils/el_nms\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBedgelab\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
