.TH "core/utils/el_base64.h" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/utils/el_base64.h
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBedgelab\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBedgelab::el_base64_encode_output\fP (const unsigned char *in, int in_len, int(*putc_func)(int))"
.br
.ti -1c
.RI "void \fBedgelab::el_base64_encode\fP (const unsigned char *in, int in_len, char *out)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
