.TH "porting/espressif/el_board_config.h" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
porting/espressif/el_board_config.h
.SH SYNOPSIS
.br
.PP
\fC#include <sdkconfig\&.h>\fP
.br
\fC#include 'boards/boards\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
