.TH "el_box_t" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
el_box_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <el_types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBx\fP"
.br
.ti -1c
.RI "uint16_t \fBy\fP"
.br
.ti -1c
.RI "uint16_t \fBw\fP"
.br
.ti -1c
.RI "uint16_t \fBh\fP"
.br
.ti -1c
.RI "uint8_t \fBscore\fP"
.br
.ti -1c
.RI "uint8_t \fBtarget\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint16_t el_box_t::h"

.SS "uint8_t el_box_t::score"

.SS "uint8_t el_box_t::target"

.SS "uint16_t el_box_t::w"

.SS "uint16_t el_box_t::x"

.SS "uint16_t el_box_t::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
