.TH "porting/el_camera.h" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
porting/el_camera.h
.SH SYNOPSIS
.br
.PP
\fC#include <cstddef>\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include 'core/el_types\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBedgelab::Camera\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBedgelab\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
