.TH "core/el_compiler.h" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/el_compiler.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBEL_LITTLE_ENDIAN\fP   (0x12u)"
.br
.ti -1c
.RI "#define \fBEL_BIG_ENDIAN\fP   (0x21u)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define EL_BIG_ENDIAN   (0x21u)"

.SS "#define EL_LITTLE_ENDIAN   (0x12u)"

.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
