.TH "core/utils/el_cv.h" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/utils/el_cv.h
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include 'core/el_types\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBedgelab\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "EL_ATTR_WEAK \fBel_err_code_t\fP \fBedgelab::el_img_convert\fP (const \fBel_img_t\fP *src, \fBel_img_t\fP *dst)"
.br
.ti -1c
.RI "EL_ATTR_WEAK void \fBedgelab::el_draw_rect\fP (\fBel_img_t\fP *img, int16_t x, int16_t y, int16_t w, int16_t h, uint32_t color, uint8_t thickness)"
.br
.ti -1c
.RI "EL_ATTR_WEAK void \fBedgelab::el_fill_rect\fP (\fBel_img_t\fP *img, int16_t x, int16_t y, int16_t w, int16_t h, uint32_t color)"
.br
.ti -1c
.RI "EL_ATTR_WEAK void \fBedgelab::el_draw_point\fP (\fBel_img_t\fP *img, int16_t x, int16_t y, uint32_t color)"
.br
.ti -1c
.RI "EL_ATTR_WEAK void \fBedgelab::el_draw_h_line\fP (\fBel_img_t\fP *img, int16_t x0, int16_t x1, int16_t y, uint32_t color)"
.br
.ti -1c
.RI "EL_ATTR_WEAK void \fBedgelab::el_draw_v_line\fP (\fBel_img_t\fP *img, int16_t x, int16_t y0, int16_t y1, uint32_t color)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
