.TH "core/utils/el_cv.cpp" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/utils/el_cv.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'el_cv\&.h'\fP
.br
\fC#include <memory>\fP
.br
\fC#include 'core/el_common\&.h'\fP
.br
\fC#include 'core/el_compiler\&.h'\fP
.br
\fC#include 'core/el_debug\&.h'\fP
.br
\fC#include 'core/el_types\&.h'\fP
.br
\fC#include 'third_party/JPEGENC/JPEGENC\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBedgelab::types::b16_t\fP"
.br
.ti -1c
.RI "struct \fBedgelab::types::b24_t\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBedgelab\fP"
.br
.ti -1c
.RI " \fBedgelab::constants\fP"
.br
.ti -1c
.RI " \fBedgelab::types\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct EL_ATTR_PACKED \fBedgelab::types::b16_t\fP \fBedgelab::types::b16_t\fP"
.br
.ti -1c
.RI "typedef struct EL_ATTR_PACKED \fBedgelab::types::b24_t\fP \fBedgelab::types::b24_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "EL_ATTR_WEAK void \fBedgelab::yuv422p_to_rgb\fP (const \fBel_img_t\fP *src, \fBel_img_t\fP *dst)"
.br
.ti -1c
.RI "EL_ATTR_WEAK void \fBedgelab::rgb888_to_rgb888\fP (const \fBel_img_t\fP *src, \fBel_img_t\fP *dst)"
.br
.ti -1c
.RI "EL_ATTR_WEAK void \fBedgelab::rgb888_to_rgb565\fP (const \fBel_img_t\fP *src, \fBel_img_t\fP *dst)"
.br
.ti -1c
.RI "EL_ATTR_WEAK void \fBedgelab::rgb888_to_gray\fP (const \fBel_img_t\fP *src, \fBel_img_t\fP *dst)"
.br
.ti -1c
.RI "EL_ATTR_WEAK void \fBedgelab::rgb565_to_rgb888\fP (const \fBel_img_t\fP *src, \fBel_img_t\fP *dst)"
.br
.ti -1c
.RI "EL_ATTR_WEAK void \fBedgelab::rgb565_to_rgb565\fP (const \fBel_img_t\fP *src, \fBel_img_t\fP *dst)"
.br
.ti -1c
.RI "EL_ATTR_WEAK void \fBedgelab::rgb565_to_gray\fP (const \fBel_img_t\fP *src, \fBel_img_t\fP *dst)"
.br
.ti -1c
.RI "EL_ATTR_WEAK void \fBedgelab::gray_to_rgb888\fP (const \fBel_img_t\fP *src, \fBel_img_t\fP *dst)"
.br
.ti -1c
.RI "EL_ATTR_WEAK void \fBedgelab::gray_to_rgb565\fP (const \fBel_img_t\fP *src, \fBel_img_t\fP *dst)"
.br
.ti -1c
.RI "EL_ATTR_WEAK void \fBedgelab::gray_to_gray\fP (const \fBel_img_t\fP *src, \fBel_img_t\fP *dst)"
.br
.ti -1c
.RI "EL_ATTR_WEAK void \fBedgelab::rgb_to_rgb\fP (const \fBel_img_t\fP *src, \fBel_img_t\fP *dst)"
.br
.ti -1c
.RI "EL_ATTR_WEAK \fBel_err_code_t\fP \fBedgelab::rgb_to_jpeg\fP (const \fBel_img_t\fP *src, \fBel_img_t\fP *dst)"
.br
.ti -1c
.RI "EL_ATTR_WEAK \fBel_err_code_t\fP \fBedgelab::el_img_convert\fP (const \fBel_img_t\fP *src, \fBel_img_t\fP *dst)"
.br
.ti -1c
.RI "EL_ATTR_WEAK void \fBedgelab::el_draw_point\fP (\fBel_img_t\fP *img, int16_t x, int16_t y, uint32_t color)"
.br
.ti -1c
.RI "EL_ATTR_WEAK void \fBedgelab::el_fill_rect\fP (\fBel_img_t\fP *img, int16_t x, int16_t y, int16_t w, int16_t h, uint32_t color)"
.br
.ti -1c
.RI "EL_ATTR_WEAK void \fBedgelab::el_draw_h_line\fP (\fBel_img_t\fP *img, int16_t x0, int16_t x1, int16_t y, uint32_t color)"
.br
.ti -1c
.RI "EL_ATTR_WEAK void \fBedgelab::el_draw_v_line\fP (\fBel_img_t\fP *img, int16_t x, int16_t y0, int16_t y1, uint32_t color)"
.br
.ti -1c
.RI "EL_ATTR_WEAK void \fBedgelab::el_draw_rect\fP (\fBel_img_t\fP *img, int16_t x, int16_t y, int16_t w, int16_t h, uint32_t color, uint8_t thickness)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
