.TH "porting/espressif/el_camera_esp.h" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
porting/espressif/el_camera_esp.h
.SH SYNOPSIS
.br
.PP
\fC#include <esp_camera\&.h>\fP
.br
\fC#include <esp_log\&.h>\fP
.br
\fC#include 'core/el_types\&.h'\fP
.br
\fC#include 'porting/el_camera\&.h'\fP
.br
\fC#include 'porting/espressif/el_board_config\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBedgelab::CameraEsp\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBedgelab\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBXCLK_FREQ_HZ\fP   15000000"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define XCLK_FREQ_HZ   15000000"

.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
