.TH "core/el_debug.h" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/el_debug.h
.SH SYNOPSIS
.br
.PP
\fC#include 'porting/el_misc\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBEL_ELOG\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBEL_LOGW\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBEL_LOGI\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBLOG_D\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBEL_ASSERT\fP(expr)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define EL_ASSERT(expr)"

.SS "#define EL_ELOG( \&.\&.\&.)"

.SS "#define EL_LOGI( \&.\&.\&.)"

.SS "#define EL_LOGW( \&.\&.\&.)"

.SS "#define LOG_D( \&.\&.\&.)"

.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
