.TH "porting/espressif/el_display_esp.h" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
porting/espressif/el_display_esp.h
.SH SYNOPSIS
.br
.PP
\fC#include <esp_log\&.h>\fP
.br
\fC#include <screen_driver\&.h>\fP
.br
\fC#include 'core/el_types\&.h'\fP
.br
\fC#include 'porting/el_display\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBedgelab::DisplayEsp\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBedgelab\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
