.TH "porting/espressif/el_device_esp.cpp" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
porting/espressif/el_device_esp.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'el_device_esp\&.h'\fP
.br
\fC#include <esp_efuse\&.h>\fP
.br
\fC#include <esp_efuse_chip\&.h>\fP
.br
\fC#include <esp_efuse_table\&.h>\fP
.br
\fC#include <hal/efuse_hal\&.h>\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include 'porting/espressif/el_camera_esp\&.h'\fP
.br
\fC#include 'porting/espressif/el_display_esp\&.h'\fP
.br
\fC#include 'porting/espressif/el_serial_esp\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBedgelab\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
