.TH "porting/espressif/el_flash_esp.cpp" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
porting/espressif/el_flash_esp.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'el_flash_esp\&.h'\fP
.br
\fC#include 'core/el_debug\&.h'\fP
.br
\fC#include 'core/synchronize/el_guard\&.hpp'\fP
.br
\fC#include 'core/synchronize/el_mutex\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBedgelab\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBel_err_code_t\fP \fBedgelab::el_model_partition_mmap_init\fP (const char *partition_name, uint32_t *partition_start_addr, uint32_t *partition_size, const uint8_t **flash_2_memory_map, spi_flash_mmap_handle_t *mmap_handler)"
.br
.ti -1c
.RI "void \fBedgelab::el_model_partition_mmap_deinit\fP (spi_flash_mmap_handle_t *mmap_handler)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const struct fal_flash_dev \fBedgelab::el_flash_db_nor_flash0\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
