.TH "core/utils/el_hash.h" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/utils/el_hash.h
.SH SYNOPSIS
.br
.PP
\fC#include <cstddef>\fP
.br
\fC#include <cstdint>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBedgelab\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "EL_ATTR_WEAK uint16_t \fBedgelab::el_crc16_maxim\fP (const uint8_t *data, size_t length)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
