.TH "el_input_t" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
el_input_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <el_types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBel_tensor_t\fP * \fBtensor\fP"
.br
.ti -1c
.RI "size_t \fBlength\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "size_t el_input_t::length"

.SS "\fBel_tensor_t\fP* el_input_t::tensor"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
