.TH "el_model_info_t" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
el_model_info_t \- Mdoel Info Specification\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <el_types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBid\fP"
.br
.ti -1c
.RI "\fBel_algorithm_type_t\fP \fBtype\fP"
.br
.ti -1c
.RI "uint32_t \fBaddr_flash\fP"
.br
.ti -1c
.RI "uint32_t \fBsize\fP"
.br
.ti -1c
.RI "const uint8_t * \fBaddr_memory\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Mdoel Info Specification\&. 

valid id range [1, 15]: 0 -> undefined each model should have a unique id valid type range [1, 15]: 0 -> undefined 1 -> FOMO 2 -> PFLD 3 -> YOLO 
.SH "Member Data Documentation"
.PP 
.SS "uint32_t el_model_info_t::addr_flash"

.SS "const uint8_t* el_model_info_t::addr_memory"

.SS "uint8_t el_model_info_t::id"

.SS "uint32_t el_model_info_t::size"

.SS "\fBel_algorithm_type_t\fP el_model_info_t::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
