.TH "core/synchronize/el_mutex.hpp" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/synchronize/el_mutex.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <freertos/FreeRTOS\&.h>\fP
.br
\fC#include <freertos/semphr\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBedgelab::Mutex\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBedgelab\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
