.TH "core/utils/el_nms.h" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/utils/el_nms.h
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include <forward_list>\fP
.br
\fC#include 'core/el_types\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBedgelab\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "EL_ATTR_WEAK int \fBedgelab::el_nms\fP (std::forward_list< \fBel_box_t\fP > &boxes, uint8_t nms_iou_thresh, uint8_t nms_score_thresh, bool soft_nms, bool multi_target)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
