.TH "el_quant_param_t" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
el_quant_param_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <el_types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBscale\fP"
.br
.ti -1c
.RI "int32_t \fBzero_point\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float el_quant_param_t::scale"

.SS "int32_t el_quant_param_t::zero_point"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
