.TH "el_shape_t" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
el_shape_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <el_types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "int * \fBdims\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int* el_shape_t::dims"

.SS "size_t el_shape_t::size"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
