.TH "el_sensor_info_t" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
el_sensor_info_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <el_types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBid\fP"
.br
.ti -1c
.RI "\fBel_sensor_type_t\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBel_sensor_state_t\fP \fBstate\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint8_t el_sensor_info_t::id"

.SS "\fBel_sensor_state_t\fP el_sensor_info_t::state"

.SS "\fBel_sensor_type_t\fP el_sensor_info_t::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
