.TH "core/el_types.h" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/el_types.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdbool\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'el_compiler\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBel_shape_t\fP"
.br
.ti -1c
.RI "struct \fBel_quant_param_t\fP"
.br
.ti -1c
.RI "struct \fBel_memory_pool_t\fP"
.br
.ti -1c
.RI "struct \fBel_box_t\fP"
.br
.ti -1c
.RI "struct \fBel_point_t\fP"
.br
.ti -1c
.RI "struct \fBel_class_t\fP"
.br
.ti -1c
.RI "struct \fBel_tensor_t\fP"
.br
.ti -1c
.RI "struct \fBel_input_t\fP"
.br
.ti -1c
.RI "struct \fBel_img_t\fP"
.br
.ti -1c
.RI "struct \fBel_res_t\fP"
.br
.ti -1c
.RI "struct \fBel_sensor_info_t\fP"
.br
.ti -1c
.RI "union \fBel_model_header_t\fP"
.br
.RI "Model Header Specification\&. "
.ti -1c
.RI "struct \fBel_model_info_t\fP"
.br
.RI "Mdoel Info Specification\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct EL_ATTR_PACKED \fBel_shape_t\fP \fBel_shape_t\fP"
.br
.ti -1c
.RI "typedef struct EL_ATTR_PACKED \fBel_quant_param_t\fP \fBel_quant_param_t\fP"
.br
.ti -1c
.RI "typedef struct EL_ATTR_PACKED \fBel_memory_pool_t\fP \fBel_memory_pool_t\fP"
.br
.ti -1c
.RI "typedef struct EL_ATTR_PACKED \fBel_box_t\fP \fBel_box_t\fP"
.br
.ti -1c
.RI "typedef struct EL_ATTR_PACKED \fBel_point_t\fP \fBel_point_t\fP"
.br
.ti -1c
.RI "typedef struct EL_ATTR_PACKED \fBel_class_t\fP \fBel_class_t\fP"
.br
.ti -1c
.RI "typedef struct EL_ATTR_PACKED \fBel_tensor_t\fP \fBel_tensor_t\fP"
.br
.ti -1c
.RI "typedef struct EL_ATTR_PACKED \fBel_input_t\fP \fBel_input_t\fP"
.br
.ti -1c
.RI "typedef enum \fBel_pixel_rotate_t\fP \fBel_pixel_rotate_t\fP"
.br
.ti -1c
.RI "typedef struct EL_ATTR_PACKED \fBel_img_t\fP \fBel_img_t\fP"
.br
.ti -1c
.RI "typedef struct EL_ATTR_PACKED \fBel_res_t\fP \fBel_res_t\fP"
.br
.ti -1c
.RI "typedef struct EL_ATTR_PACKED \fBel_sensor_info_t\fP \fBel_sensor_info_t\fP"
.br
.ti -1c
.RI "typedef int \fBel_model_format_v\fP"
.br
.ti -1c
.RI "typedef union EL_ATTR_PACKED \fBel_model_header_t\fP \fBel_model_header_t\fP"
.br
.RI "Model Header Specification\&. "
.ti -1c
.RI "typedef struct EL_ATTR_PACKED \fBel_model_info_t\fP \fBel_model_info_t\fP"
.br
.RI "Mdoel Info Specification\&. "
.ti -1c
.RI "typedef uint8_t \fBel_model_id_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBel_err_code_t\fP { \fBEL_OK\fP = 0, \fBEL_AGAIN\fP = 1, \fBEL_ELOG\fP = 2, \fBEL_ETIMOUT\fP = 3, \fBEL_EIO\fP = 4, \fBEL_EINVAL\fP = 5, \fBEL_ENOMEM\fP = 6, \fBEL_EBUSY\fP = 7, \fBEL_ENOTSUP\fP = 8, \fBEL_EPERM\fP = 9 }"
.br
.ti -1c
.RI "enum \fBel_pixel_format_t\fP { \fBEL_PIXEL_FORMAT_RGB888\fP = 0, \fBEL_PIXEL_FORMAT_RGB565\fP, \fBEL_PIXEL_FORMAT_YUV422\fP, \fBEL_PIXEL_FORMAT_GRAYSCALE\fP, \fBEL_PIXEL_FORMAT_JPEG\fP, \fBEL_PIXEL_FORMAT_UNKNOWN\fP }"
.br
.ti -1c
.RI "enum \fBel_pixel_rotate_t\fP { \fBEL_PIXEL_ROTATE_0\fP = 0, \fBEL_PIXEL_ROTATE_90\fP, \fBEL_PIXEL_ROTATE_180\fP, \fBEL_PIXEL_ROTATE_270\fP, \fBEL_PIXEL_ROTATE_UNKNOWN\fP }"
.br
.ti -1c
.RI "enum \fBel_sensor_type_t\fP { \fBEL_SENSOR_TYPE_CAM\fP = 1u }"
.br
.ti -1c
.RI "enum \fBel_sensor_state_t\fP { \fBEL_SENSOR_STA_REG\fP = 0u, \fBEL_SENSOR_STA_AVAIL\fP = 1u, \fBEL_SENSOR_STA_LOCKED\fP = 2u }"
.br
.ti -1c
.RI "enum \fBel_model_format_t\fP { \fBEL_MODEL_FMT_UNDEFINED\fP = 0u, \fBEL_MODEL_FMT_PACKED_TFLITE\fP = 1u, \fBEL_MODEL_FMT_PLAIN_TFLITE\fP = 2u }"
.br
.ti -1c
.RI "enum \fBel_algorithm_type_t\fP { \fBEL_ALGO_TYPE_UNDEFINED\fP = 0u, \fBEL_ALGO_TYPE_FOMO\fP = 1u, \fBEL_ALGO_TYPE_PFLD\fP = 2u, \fBEL_ALGO_TYPE_YOLO\fP = 3u, \fBEL_ALGO_TYPE_IMCLS\fP = 4u }"
.br
.RI "Algorithm Types\&. "
.ti -1c
.RI "enum \fBel_algorithm_cat_t\fP { \fBEL_ALGO_CAT_UNDEFINED\fP = 0u, \fBEL_ALGO_CAT_DET\fP = 1u, \fBEL_ALGO_CAT_POSE\fP = 2u, \fBEL_ALGO_CAT_CLS\fP = 3u }"
.br
.RI "Algorithm Catagories\&. "
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct EL_ATTR_PACKED \fBel_box_t\fP \fBel_box_t\fP"

.SS "typedef struct EL_ATTR_PACKED \fBel_class_t\fP \fBel_class_t\fP"

.SS "typedef struct EL_ATTR_PACKED \fBel_img_t\fP \fBel_img_t\fP"

.SS "typedef struct EL_ATTR_PACKED \fBel_input_t\fP \fBel_input_t\fP"

.SS "typedef struct EL_ATTR_PACKED \fBel_memory_pool_t\fP \fBel_memory_pool_t\fP"

.SS "typedef int \fBel_model_format_v\fP"

.SS "typedef union EL_ATTR_PACKED \fBel_model_header_t\fP \fBel_model_header_t\fP"

.PP
Model Header Specification\&. [ 24 bits magic code | 4 bits id | 4 bits type | 24 bits size (unsigned) | 8 bits unused padding ] big-endian in file 
.SS "typedef uint8_t \fBel_model_id_t\fP"

.SS "typedef struct EL_ATTR_PACKED \fBel_model_info_t\fP \fBel_model_info_t\fP"

.PP
Mdoel Info Specification\&. valid id range [1, 15]: 0 -> undefined each model should have a unique id valid type range [1, 15]: 0 -> undefined 1 -> FOMO 2 -> PFLD 3 -> YOLO 
.SS "typedef enum \fBel_pixel_rotate_t\fP \fBel_pixel_rotate_t\fP"

.SS "typedef struct EL_ATTR_PACKED \fBel_point_t\fP \fBel_point_t\fP"

.SS "typedef struct EL_ATTR_PACKED \fBel_quant_param_t\fP \fBel_quant_param_t\fP"

.SS "typedef struct EL_ATTR_PACKED \fBel_res_t\fP \fBel_res_t\fP"

.SS "typedef struct EL_ATTR_PACKED \fBel_sensor_info_t\fP \fBel_sensor_info_t\fP"

.SS "typedef struct EL_ATTR_PACKED \fBel_shape_t\fP \fBel_shape_t\fP"

.SS "typedef struct EL_ATTR_PACKED \fBel_tensor_t\fP \fBel_tensor_t\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBel_algorithm_cat_t\fP"

.PP
Algorithm Catagories\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIEL_ALGO_CAT_UNDEFINED \fP\fP
.TP
\fB\fIEL_ALGO_CAT_DET \fP\fP
.TP
\fB\fIEL_ALGO_CAT_POSE \fP\fP
.TP
\fB\fIEL_ALGO_CAT_CLS \fP\fP
.SS "enum \fBel_algorithm_type_t\fP"

.PP
Algorithm Types\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIEL_ALGO_TYPE_UNDEFINED \fP\fP
.TP
\fB\fIEL_ALGO_TYPE_FOMO \fP\fP
.TP
\fB\fIEL_ALGO_TYPE_PFLD \fP\fP
.TP
\fB\fIEL_ALGO_TYPE_YOLO \fP\fP
.TP
\fB\fIEL_ALGO_TYPE_IMCLS \fP\fP
.SS "enum \fBel_err_code_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIEL_OK \fP\fP
.TP
\fB\fIEL_AGAIN \fP\fP
.TP
\fB\fIEL_ELOG \fP\fP
.TP
\fB\fIEL_ETIMOUT \fP\fP
.TP
\fB\fIEL_EIO \fP\fP
.TP
\fB\fIEL_EINVAL \fP\fP
.TP
\fB\fIEL_ENOMEM \fP\fP
.TP
\fB\fIEL_EBUSY \fP\fP
.TP
\fB\fIEL_ENOTSUP \fP\fP
.TP
\fB\fIEL_EPERM \fP\fP
.SS "enum \fBel_model_format_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIEL_MODEL_FMT_UNDEFINED \fP\fP
.TP
\fB\fIEL_MODEL_FMT_PACKED_TFLITE \fP\fP
.TP
\fB\fIEL_MODEL_FMT_PLAIN_TFLITE \fP\fP
.SS "enum \fBel_pixel_format_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIEL_PIXEL_FORMAT_RGB888 \fP\fP
.TP
\fB\fIEL_PIXEL_FORMAT_RGB565 \fP\fP
.TP
\fB\fIEL_PIXEL_FORMAT_YUV422 \fP\fP
.TP
\fB\fIEL_PIXEL_FORMAT_GRAYSCALE \fP\fP
.TP
\fB\fIEL_PIXEL_FORMAT_JPEG \fP\fP
.TP
\fB\fIEL_PIXEL_FORMAT_UNKNOWN \fP\fP
.SS "enum \fBel_pixel_rotate_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIEL_PIXEL_ROTATE_0 \fP\fP
.TP
\fB\fIEL_PIXEL_ROTATE_90 \fP\fP
.TP
\fB\fIEL_PIXEL_ROTATE_180 \fP\fP
.TP
\fB\fIEL_PIXEL_ROTATE_270 \fP\fP
.TP
\fB\fIEL_PIXEL_ROTATE_UNKNOWN \fP\fP
.SS "enum \fBel_sensor_state_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIEL_SENSOR_STA_REG \fP\fP
.TP
\fB\fIEL_SENSOR_STA_AVAIL \fP\fP
.TP
\fB\fIEL_SENSOR_STA_LOCKED \fP\fP
.SS "enum \fBel_sensor_type_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIEL_SENSOR_TYPE_CAM \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
