.TH "sscma/repl/executor.hpp" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sscma/repl/executor.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <freertos/FreeRTOS\&.h>\fP
.br
\fC#include <freertos/task\&.h>\fP
.br
\fC#include <atomic>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <queue>\fP
.br
\fC#include <utility>\fP
.br
\fC#include 'core/synchronize/el_guard\&.hpp'\fP
.br
\fC#include 'core/synchronize/el_mutex\&.hpp'\fP
.br
\fC#include 'sscma/definations\&.hpp'\fP
.br
\fC#include 'sscma/types\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsscma::repl::Executor\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsscma\fP"
.br
.ti -1c
.RI " \fBsscma::repl\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
