.TH "sscma/callback/invoke.hpp" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sscma/callback/invoke.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <atomic>\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'sscma/definations\&.hpp'\fP
.br
\fC#include 'sscma/static_resourse\&.hpp'\fP
.br
\fC#include 'sscma/utility\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsscma\fP"
.br
.ti -1c
.RI " \fBsscma::callback\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename AlgorithmType > void \fBsscma::callback::run_invoke_on_img\fP (AlgorithmType *algorithm, const std::string &cmd, int n_times, bool result_only, std::atomic< bool > &stop_token)"
.br
.ti -1c
.RI "void \fBsscma::callback::run_invoke\fP (const std::string &cmd, int n_times, bool result_only, std::atomic< bool > &stop_token)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
