.TH "sscma/interpreter/literals.hpp" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sscma/interpreter/literals.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'sscma/interpreter/types\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsscma\fP"
.br
.ti -1c
.RI " \fBsscma::interpreter\fP"
.br
.ti -1c
.RI " \fBsscma::interpreter::literals\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBsscma::interpreter::literals::operator<<\fP (std::ostream &os, \fBTokenType\fP token_type)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
