.TH "sscma/main_task.hpp" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sscma/main_task.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'sscma/callback/action\&.hpp'\fP
.br
\fC#include 'sscma/callback/algorithm\&.hpp'\fP
.br
\fC#include 'sscma/callback/default\&.hpp'\fP
.br
\fC#include 'sscma/callback/info\&.hpp'\fP
.br
\fC#include 'sscma/callback/invoke\&.hpp'\fP
.br
\fC#include 'sscma/callback/model\&.hpp'\fP
.br
\fC#include 'sscma/callback/sample\&.hpp'\fP
.br
\fC#include 'sscma/callback/sensor\&.hpp'\fP
.br
\fC#include 'sscma/static_resourse\&.hpp'\fP
.br
\fC#include 'sscma/types\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsscma\fP"
.br
.ti -1c
.RI " \fBsscma::main_task\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsscma::main_task::run\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
