.TH "sscma/interpreter/nodes.hpp" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sscma/interpreter/nodes.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'sscma/interpreter/types\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsscma::interpreter::IdentifierNode\fP"
.br
.ti -1c
.RI "class \fBsscma::interpreter::ConstantNode\fP"
.br
.ti -1c
.RI "class \fBsscma::interpreter::BinaryOperatorNode\fP"
.br
.ti -1c
.RI "class \fBsscma::interpreter::FunctionCallNode\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsscma\fP"
.br
.ti -1c
.RI " \fBsscma::interpreter\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
