.TH "sscma/repl/server.hpp" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sscma/repl/server.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <forward_list>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'core/el_types\&.h'\fP
.br
\fC#include 'core/synchronize/el_guard\&.hpp'\fP
.br
\fC#include 'core/synchronize/el_mutex\&.hpp'\fP
.br
\fC#include 'sscma/repl/history\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBsscma::types::repl_cmd_t\fP"
.br
.ti -1c
.RI "class \fBsscma::repl::Server\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsscma\fP"
.br
.ti -1c
.RI " \fBsscma::repl\fP"
.br
.ti -1c
.RI " \fBsscma::types\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::function< void(\fBel_err_code_t\fP, const std::string &)> \fBsscma::types::repl_echo_cb_t\fP"
.br
.ti -1c
.RI "typedef std::function< \fBel_err_code_t\fP(std::vector< std::string >)> \fBsscma::types::repl_cmd_cb_t\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
