.TH "sscma::interpreter::Condition" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sscma::interpreter::Condition
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <condition\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCondition\fP ()"
.br
.ti -1c
.RI "\fB~Condition\fP ()"
.br
.ti -1c
.RI "bool \fBhas_condition\fP ()"
.br
.ti -1c
.RI "bool \fBset_condition\fP (const std::string &input)"
.br
.ti -1c
.RI "const \fBmutable_map_t\fP & \fBget_mutable_map\fP ()"
.br
.ti -1c
.RI "void \fBset_mutable_map\fP (const \fBmutable_map_t\fP &map)"
.br
.ti -1c
.RI "void \fBset_true_cb\fP (\fBbranch_cb_t\fP cb)"
.br
.ti -1c
.RI "void \fBset_false_cb\fP (\fBbranch_cb_t\fP cb)"
.br
.ti -1c
.RI "void \fBset_exception_cb\fP (\fBbranch_cb_t\fP cb)"
.br
.ti -1c
.RI "void \fBevalute\fP ()"
.br
.ti -1c
.RI "void \fBunset_condition\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sscma::interpreter::Condition::Condition ()\fC [inline]\fP"

.SS "sscma::interpreter::Condition::~Condition ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void sscma::interpreter::Condition::evalute ()\fC [inline]\fP"

.SS "const \fBmutable_map_t\fP& sscma::interpreter::Condition::get_mutable_map ()\fC [inline]\fP"

.SS "bool sscma::interpreter::Condition::has_condition ()\fC [inline]\fP"

.SS "bool sscma::interpreter::Condition::set_condition (const std::string & input)\fC [inline]\fP"

.SS "void sscma::interpreter::Condition::set_exception_cb (\fBbranch_cb_t\fP cb)\fC [inline]\fP"

.SS "void sscma::interpreter::Condition::set_false_cb (\fBbranch_cb_t\fP cb)\fC [inline]\fP"

.SS "void sscma::interpreter::Condition::set_mutable_map (const \fBmutable_map_t\fP & map)\fC [inline]\fP"

.SS "void sscma::interpreter::Condition::set_true_cb (\fBbranch_cb_t\fP cb)\fC [inline]\fP"

.SS "void sscma::interpreter::Condition::unset_condition ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
