.TH "sscma::interpreter::types::Token" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sscma::interpreter::types::Token
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTokenType\fP \fBtype\fP"
.br
.ti -1c
.RI "std::string \fBvalue\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBTokenType\fP sscma::interpreter::types::Token::type"

.SS "std::string sscma::interpreter::types::Token::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
