.TH "sscma::callback::AlgorithmConfigHelper< AlgorithmType >" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sscma::callback::AlgorithmConfigHelper< AlgorithmType >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <algorithm_config_helper\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBConfigType\fP = typename AlgorithmType::ConfigType"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAlgorithmConfigHelper\fP (AlgorithmType *algorithm)"
.br
.ti -1c
.RI "\fBConfigType\fP \fBdump_config\fP ()"
.br
.ti -1c
.RI "\fB~AlgorithmConfigHelper\fP ()"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename AlgorithmType > using \fBsscma::callback::AlgorithmConfigHelper\fP< AlgorithmType >::\fBConfigType\fP =  typename AlgorithmType::ConfigType"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename AlgorithmType > \fBsscma::callback::AlgorithmConfigHelper\fP< AlgorithmType >::\fBAlgorithmConfigHelper\fP (AlgorithmType * algorithm)\fC [inline]\fP"

.SS "template<typename AlgorithmType > \fBsscma::callback::AlgorithmConfigHelper\fP< AlgorithmType >::~\fBAlgorithmConfigHelper\fP ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename AlgorithmType > \fBConfigType\fP \fBsscma::callback::AlgorithmConfigHelper\fP< AlgorithmType >::dump_config ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
