.TH "sscma::interpreter::ConstantNode" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sscma::interpreter::ConstantNode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nodes\&.hpp>\fP
.PP
Inherits \fBsscma::interpreter::types::ASTNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConstantNode\fP (const std::string &value)"
.br
.ti -1c
.RI "\fB~ConstantNode\fP ()=default"
.br
.ti -1c
.RI "\fBResult\fP \fBevaluate\fP (\fBEvalCallback\fP) const override"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sscma::interpreter::ConstantNode::ConstantNode (const std::string & value)\fC [inline]\fP"

.SS "sscma::interpreter::ConstantNode::~ConstantNode ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBResult\fP sscma::interpreter::ConstantNode::evaluate (\fBEvalCallback\fP) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBsscma::interpreter::types::ASTNode\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
