.TH "sscma::interpreter::utility" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sscma::interpreter::utility
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBis_identifier\fP (char c)"
.br
.ti -1c
.RI "bool \fBis_constant\fP (char c)"
.br
.ti -1c
.RI "bool \fBis_arithmetic_operator\fP (char c)"
.br
.ti -1c
.RI "bool \fBis_relational_operator_pred\fP (char c)"
.br
.ti -1c
.RI "bool \fBis_relational_operator_term\fP (char c)"
.br
.ti -1c
.RI "bool \fBis_logical_operator\fP (char c)"
.br
.ti -1c
.RI "bool \fBis_lparn\fP (char c)"
.br
.ti -1c
.RI "bool \fBis_rparn\fP (char c)"
.br
.ti -1c
.RI "bool \fBis_comma\fP (char c)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool sscma::interpreter::utility::is_arithmetic_operator (char c)"

.SS "bool sscma::interpreter::utility::is_comma (char c)"

.SS "bool sscma::interpreter::utility::is_constant (char c)"

.SS "bool sscma::interpreter::utility::is_identifier (char c)"

.SS "bool sscma::interpreter::utility::is_logical_operator (char c)"

.SS "bool sscma::interpreter::utility::is_lparn (char c)"

.SS "bool sscma::interpreter::utility::is_relational_operator_pred (char c)"

.SS "bool sscma::interpreter::utility::is_relational_operator_term (char c)"

.SS "bool sscma::interpreter::utility::is_rparn (char c)"

.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
