.TH "sscma::interpreter::types" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sscma::interpreter::types
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBToken\fP"
.br
.ti -1c
.RI "struct \fBResult\fP"
.br
.ti -1c
.RI "class \fBASTNode\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::vector< \fBToken\fP > \fBMutables\fP"
.br
.ti -1c
.RI "typedef std::function< \fBResult\fP(\fBNodeType\fP, const std::string &)> \fBEvalCallback\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBTokenType\fP { \fBIDENTIFIER\fP, \fBCONSTANT\fP, \fBOPERATOR\fP, \fBLPARN\fP, \fBRPARN\fP, \fBFUNCTION\fP, \fBTERM\fP }"
.br
.ti -1c
.RI "enum class \fBNodeType\fP { \fBIDENTIFIER\fP, \fBFUNCTION_CALL\fP }"
.br
.ti -1c
.RI "enum class \fBEvalStatus\fP { \fBOK\fP, \fBEXCEPTION\fP }"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::function<\fBResult\fP(\fBNodeType\fP, const std::string&)> \fBsscma::interpreter::types::EvalCallback\fP"

.SS "typedef std::vector<\fBToken\fP> \fBsscma::interpreter::types::Mutables\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBsscma::interpreter::types::EvalStatus\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOK \fP\fP
.TP
\fB\fIEXCEPTION \fP\fP
.SS "enum \fBsscma::interpreter::types::NodeType\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIIDENTIFIER \fP\fP
.TP
\fB\fIFUNCTION_CALL \fP\fP
.SS "enum \fBsscma::interpreter::types::TokenType\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIIDENTIFIER \fP\fP
.TP
\fB\fICONSTANT \fP\fP
.TP
\fB\fIOPERATOR \fP\fP
.TP
\fB\fILPARN \fP\fP
.TP
\fB\fIRPARN \fP\fP
.TP
\fB\fIFUNCTION \fP\fP
.TP
\fB\fITERM \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
