.TH "sscma::interpreter::BinaryOperatorNode" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sscma::interpreter::BinaryOperatorNode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nodes\&.hpp>\fP
.PP
Inherits \fBsscma::interpreter::types::ASTNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBinaryOperatorNode\fP (const std::string &operator_name, \fBASTNode\fP *left, \fBASTNode\fP *right)"
.br
.ti -1c
.RI "\fB~BinaryOperatorNode\fP ()"
.br
.ti -1c
.RI "\fBResult\fP \fBevaluate\fP (\fBEvalCallback\fP callback) const override"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sscma::interpreter::BinaryOperatorNode::BinaryOperatorNode (const std::string & operator_name, \fBASTNode\fP * left, \fBASTNode\fP * right)\fC [inline]\fP"

.SS "sscma::interpreter::BinaryOperatorNode::~BinaryOperatorNode ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBResult\fP sscma::interpreter::BinaryOperatorNode::evaluate (\fBEvalCallback\fP callback) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBsscma::interpreter::types::ASTNode\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
