.TH "sscma::interpreter::FunctionCallNode" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sscma::interpreter::FunctionCallNode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nodes\&.hpp>\fP
.PP
Inherits \fBsscma::interpreter::types::ASTNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFunctionCallNode\fP (const std::string &function_call)"
.br
.ti -1c
.RI "\fB~FunctionCallNode\fP ()=default"
.br
.ti -1c
.RI "\fBResult\fP \fBevaluate\fP (\fBEvalCallback\fP callback) const override"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sscma::interpreter::FunctionCallNode::FunctionCallNode (const std::string & function_call)\fC [inline]\fP"

.SS "sscma::interpreter::FunctionCallNode::~FunctionCallNode ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBResult\fP sscma::interpreter::FunctionCallNode::evaluate (\fBEvalCallback\fP callback) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBsscma::interpreter::types::ASTNode\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
