.TH "sscma::definations" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sscma::definations
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBdelim_f_t\fP = std::function< void(std::ostringstream &os)>"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBsscma::definations::delim_f_t\fP = typedef std::function<void(std::ostringstream& os)>"

.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
