.TH "sscma::types" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sscma::types
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBrepl_cmd_t\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::function< void(\fBel_err_code_t\fP, const std::string &)> \fBrepl_echo_cb_t\fP"
.br
.ti -1c
.RI "typedef std::function< \fBel_err_code_t\fP(std::vector< std::string >)> \fBrepl_cmd_cb_t\fP"
.br
.ti -1c
.RI "typedef std::function< void(std::atomic< bool > &)> \fBrepl_task_t\fP"
.br
.ti -1c
.RI "typedef std::function< void(void)> \fBbranch_cb_t\fP"
.br
.ti -1c
.RI "typedef std::function< int(void)> \fBmutable_cb_t\fP"
.br
.ti -1c
.RI "typedef std::unordered_map< std::string, \fBmutable_cb_t\fP > \fBmutable_map_t\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::function<void(void)> \fBsscma::types::branch_cb_t\fP"

.SS "typedef std::function<int(void)> \fBsscma::types::mutable_cb_t\fP"

.SS "typedef std::unordered_map<std::string, \fBmutable_cb_t\fP> \fBsscma::types::mutable_map_t\fP"

.SS "typedef std::function<\fBel_err_code_t\fP(std::vector<std::string>)> \fBsscma::types::repl_cmd_cb_t\fP"

.SS "typedef std::function<void(\fBel_err_code_t\fP, const std::string&)> \fBsscma::types::repl_echo_cb_t\fP"

.SS "typedef std::function<void(std::atomic<bool>&)> \fBsscma::types::repl_task_t\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
