.TH "sscma::types::repl_cmd_t" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sscma::types::repl_cmd_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <server\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBrepl_cmd_t\fP (std::string cmd_, std::string desc_, std::string args_, \fBrepl_cmd_cb_t\fP cmd_cb_)"
.br
.ti -1c
.RI "\fB~repl_cmd_t\fP ()=default"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBcmd\fP"
.br
.ti -1c
.RI "std::string \fBdesc\fP"
.br
.ti -1c
.RI "std::string \fBargs\fP"
.br
.ti -1c
.RI "\fBrepl_cmd_cb_t\fP \fBcmd_cb\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBsscma::repl::Server\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sscma::types::repl_cmd_t::repl_cmd_t (std::string cmd_, std::string desc_, std::string args_, \fBrepl_cmd_cb_t\fP cmd_cb_)\fC [inline]\fP"

.SS "sscma::types::repl_cmd_t::~repl_cmd_t ()\fC [default]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBsscma::repl::Server\fP\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string sscma::types::repl_cmd_t::args"

.SS "std::string sscma::types::repl_cmd_t::cmd"

.SS "\fBrepl_cmd_cb_t\fP sscma::types::repl_cmd_t::cmd_cb"

.SS "std::string sscma::types::repl_cmd_t::desc"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
