.TH "sscma::interpreter::Parser" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sscma::interpreter::Parser
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parser\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParser\fP (\fBLexer\fP &lexer, \fBMutables\fP &mut)"
.br
.ti -1c
.RI "\fB~Parser\fP ()=default"
.br
.ti -1c
.RI "\fBASTNode\fP * \fBparse\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBparse_expression\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sscma::interpreter::Parser::Parser (\fBLexer\fP & lexer, \fBMutables\fP & mut)\fC [inline]\fP"

.SS "sscma::interpreter::Parser::~Parser ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBASTNode\fP* sscma::interpreter::Parser::parse ()\fC [inline]\fP"

.SS "bool sscma::interpreter::Parser::parse_expression ()\fC [inline]\fP, \fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
