.TH "tflite::OpsResolver" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tflite::OpsResolver
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <el_engine_tflite\&.h>\fP
.PP
Inherits MicroMutableOpResolver< OpsCount::OpsTail \- OpsCount::OpsHead >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOpsResolver\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tflite::OpsResolver::OpsResolver ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
