.TH "tflite" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tflite
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOpsResolver\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBOpsCount\fP : unsigned int { \fBOpsHead\fP = 0, \fBAddIf\fP, \fBOpsTail\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBtflite::OpsCount\fP : unsigned int"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOpsHead \fP\fP
.TP
\fB\fIAddIf \fP\fP
.TP
\fB\fIOpsTail \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
