.TH "sscma/types.hpp" 3 "Sun Sep 17 2023" "Version v2023.09.15" "SSCMA-Micro CPP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sscma/types.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <atomic>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <string>\fP
.br
\fC#include <unordered_map>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsscma\fP"
.br
.ti -1c
.RI " \fBsscma::types\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::function< void(std::atomic< bool > &)> \fBsscma::types::repl_task_t\fP"
.br
.ti -1c
.RI "typedef std::function< void(void)> \fBsscma::types::branch_cb_t\fP"
.br
.ti -1c
.RI "typedef std::function< int(void)> \fBsscma::types::mutable_cb_t\fP"
.br
.ti -1c
.RI "typedef std::unordered_map< std::string, mutable_cb_t > \fBsscma::types::mutable_map_t\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SSCMA-Micro CPP SDK from the source code\&.
